apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devops-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-devops-app
  template:
    metadata:
      labels:
        app: my-devops-app
    spec:
      containers:
        - name: my-devops-app
          image: dydcjsrjaror/my-devops-app:d65b9ef6311a226ce3a9f944f6e731bc6e42f720
          ports:
            - containerPort: 80