apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devops-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-devops-app
  template:
    metadata:
      labels:
        app: my-devops-app
    spec:
      containers:
        - name: my-devops-app
          image: dydcjsrjaror/my-devops-app:7b621f2b55b67b78f248cb27e9fda2d112e0b10f
          ports:
            - containerPort: 80